#!/usr/bin/python3

# we assume a fair player.

import math

# in this interactive while loop, the script explains the game, gets highest integer of range from user;
# and initializes floor and ceiling variables
while True:
    print("in this game you give me a range of integers from 1 to some number you choose." + '\n' +
    "then you will pick a number within this range for me to guess." + '\n' +
    "i will try to guess your number in the fewest number of tries." + '\n' +
    "for each guess, you will tell me if your number is higher than (h)," + '\n' +
    "lower than (l), or equal to (=) your number. ready?" + '\n')

    floor = 1
    ceiling = input("please enter the highest number of your range: ")

    # remember that the 'break' statement lets the program counter
    # leave the innermost loop structure that it's in.
    # that how we 'break out' of the infinite loop.
    # 'continue' is related to 'break' ---
    # it returns the program counter to the top of the while loop.
    if not isinstance(ceiling, int) and\
       not ceiling > 1:
        print("that's not a legitimate value. please enter a counting number greater than 1.")
        continue

# print the challenge of fewest guesses using this algorithm
# use math.ceil() and math.log() functions

# initalize the guess counter
guessCnt = 0
while True:
    guessCnt = guessCnt + 1
    guess = (floor + ceiling)//2

    answer = input("i guess " + str(guess) + "! Is your number higher (h), lower (l), or equal (=)? ")

    # RUMPELSTILTSKIN LINES
    # several if-statements, each processing different user input

